### ISSUE TITLE
Get "None" when y try to get item price from amazon

### ISSUE THREAD

**Issue by kohonez** [mehtaarn000/PriceHero#6]
```
import PriceHero as ph

laptop = ph.amazon("https://www.amazon.com/dp/B08FJ6ZB4V")
print(laptop)
```

{'name': 'GeIL Orion DDR4 RAM, 32GB (16GBx2) 3600MHz 1.35V XMP2.0, Intel/AMD Compatible, Long DIMM High Speed Desktop Memory, Hardcore Immersive Gaming/Multimedia Content Creation/Quality Live Streaming', 'price': None}

**Comment by mehtaarn000** [comment]
Hi @kohonez! Cam you give me the version of PriceHero that you are using. Do this:
```
import PriceHero as ph
print(ph.__version__)
```

Thanks!

**Comment by mehtaarn000** [comment]
Ok, the new version (0.5.2) should fix this bug. You can update PriceHero by running:
`pip install --upgrade PriceHero-mehtaarn000`

Let me know if you still have issues with this module.

**Comment by kohonez** [comment]
ooops! i was trying with newegg by mistake.. still have issues with amazon :(.. 

```
import PriceHero as ph
print(ph.__version__)

laptop = ph.amazon("https://www.amazon.com/dp/B08FJ6ZB4V")
print(laptop)
```

**OUTPUT:**
0.5.2
{'name': 'GeIL Orion DDR4 RAM, 32GB (16GBx2) 3600MHz 1.35V XMP2.0, Intel/AMD Compatible, Long DIMM High Speed Desktop Memory, Hardcore Immersive Gaming/Multimedia Content Creation/Quality Live Streaming', 'price': None}

**Comment by mehtaarn000** [comment]
That's really strange. When I run the code:
```
import PriceHero as ph
print(ph.__version__)

laptop = ph.amazon("https://www.amazon.com/dp/B08FJ6ZB4V")
print(laptop)
```
I get:

0.5.2
{'name': 'GeIL Orion DDR4 RAM, 32GB (16GBx2) 3600MHz 1.35V XMP2.0, Intel/AMD Compatible, Long DIMM High Speed Desktop Memory, Hardcore Immersive Gaming/Multimedia Content Creation/Quality Live Streaming', 'price': '$185.99'}

It might have to do with your OS. Can you tell me what operating system you are using?

**Comment by kohonez** [comment]
Win7 64 bits

**Comment by kohonez** [comment]
let me try in a Linux box..

**Comment by kohonez** [comment]
![image](https://user-images.githubusercontent.com/2554760/113649045-bfdc2c80-965b-11eb-9ee1-5e7c88939f7f.png)
same in Ubuntu 18.04 LTS

**Comment by mehtaarn000** [comment]
After fixing this module and testing on a Windows 10 machine I got the expected output on both of my computers. Upgrade your version again and try. Let me know again if any errors occur!

**Comment by kohonez** [comment]
Same, i'd tried in local Win7/Linux machines and a VPS with different ip, it's the same error.

**Comment by mehtaarn000** [comment]
Ok, I'm not really sure what's going wrong here. I'm going to try and tackle this tomorrow after getting some sleep. Thanks for notifying be about this issue though!

**Comment by kilianplapp** [comment]
Is it possible you might have encountered some sort of scrape/automation blocking page from amazon?

**Comment by kilianplapp** [comment]
I cannot replicate this problem on a Windows 10 64bit PC running Python 3.9.4

**Comment by mehtaarn000** [comment]
@kilianalias Meaning you get the expected output?

**Comment by kilianplapp** [comment]
Yes, I get the expected output.
